### ISSUE TITLE
Pouët "à la main"

### ISSUE THREAD

**Issue by SGallay** [kernox/Mastodon-Share-for-WordPress#10]
La nouvelle version de Mastodon Share semble ne plus prendre en compte les préférences de compositions du pouët dans les réglages. Le nouveau champ reste vide et il faut ajouter soi-même les éléments, y compris l'URL (mais il publie l'image).

**Comment by kernox** [comment]
Salut,

Peux tu tester la derniere version et fermer ce ticket si le bug n'est plus ?

Merci

**Comment by SGallay** [comment]
Alors j'ai parfois l'apparition d'un "loading please wait" dans la fenêtre, qui disparaît quand on recharge la page, parfois pas. Je me demande si ce n'est pas lié à la configuration des ad/tracker blockers.

**Comment by kernox** [comment]
Bonjour,

Ton idée concernant les adblockers est intéressante. Je vais voir s'il y a un lien.
Merci pour ton retour, je te tiens au courant de mes avancées sur le sujet.

**Comment by kernox** [comment]
Je ferme cet issue car son sujet d'origine est reglè.

**Comment by kernox** [comment]
#16
