### ISSUE TITLE
Plugin stopped working?

### ISSUE THREAD

**Issue by SunDancerGE** [kernox/Mastodon-Share-for-WordPress#12]
A few days ago the plugin stopped tooting links from where my blogpost came and as of now it doesn't toot anything anymore. :S

**Comment by scroom** [comment]
Installed it and tried today to post an article as well to Mastodon. Didn't work either.

**Comment by kernox** [comment]
It can be a problem with your instance. If the plugin worked before.
I actually fix some bug, but what you describe is not in the issues showed.

**Comment by SunDancerGE** [comment]
at the moment it does post but on my blog it butchers the permalink so that I have to add that manually.

**Comment by kernox** [comment]
When you create your post, nothing is able to construct the permalink. If you wait the wordpress autosave, the permalink normally appear.

Because, the plugin use what is able on html and javascript sources. Some elements can't be constructed at some moment.

**Comment by scroom** [comment]
@kernox I'm as well the instance admin. So if you want to I can provide you with logs of the blog and of the instance. Just tell me if you need some logs.

**Comment by kernox** [comment]
I just pushed the new version 0.9.
Some bugs are fixed. Please update and test ;)
