### ISSUE TITLE
URL longues tronquées

### ISSUE THREAD

**Issue by SGallay** [kernox/Mastodon-Share-for-WordPress#13]
Il semble que, si une URL est trop longue, elle est tronquée par le plug-in.

Exemple ici: https://framapiaf.org/@Alias/99256678487864816

Lien originel: https://alias.erdorin.org/futur-nest-plus-quil-etait-conference-de-charles-stross/

**Comment by kernox** [comment]
Effectivement il y a bien un bug sur les URL trop longues liées a des titre trop long.
Stay in touch

**Comment by kernox** [comment]
Le bug est corrigé
