### ISSUE TITLE
Localisation of the plugin

### ISSUE THREAD

**Issue by scroom** [kernox/Mastodon-Share-for-WordPress#14]
Hello,

today I've installed your plugin. Seems to work properly. But I realized that the plugin isn't translated in german for example. 
I could imagine to do this if you would give me a helping hand how to do this.

**Comment by kernox** [comment]
Hello, thank you for your interest.
If you want to translate the plugin in german you need to go at this address : 

https://translate.wordpress.org/projects/wp-plugins/wp-mastodon-share

**Comment by scroom** [comment]
I've done so.

**Comment by kernox** [comment]
Ok now we need toi wait until WordPress team validate thé translation.

Thanks for your contribution

**Comment by kernox** [comment]
Hi !

German language is now available.
Thank you for your translation and Happy New Year
