### ISSUE TITLE
Changement de token à chaque mise à jour/réinstallation du plug-in?

### ISSUE THREAD

**Issue by SGallay** [kernox/Mastodon-Share-for-WordPress#17]
Lorsque j'ai fait la mise à jour du plug-in vers la version 0.9, j'ai dû demander un nouveau token, mais je n'ai vu que celui que j'avais n'était plus valable que quand j'ai essayer d'envoyer un nouvel article vers Mastodon.

Idem quand j'ai réinstallé "from scratch" (OK, ça c'est plus normal).

Suggestion: avoir une fonction qui permette de tester la validité du token depuis les réglages, voire automatiquement.

**Comment by kernox** [comment]
Bonjour,
J’opère actuellement une modification pour qu'il n'y ai pas besoin de redemander un token à chaque mise à jour. Cet aspect est dut a l'utilisation de la librairie TootoPHP qui crée actuellement un fichier pour conserver le token. La prochaine version rendra beaucoup plus simple l'authentification.

Concernant ta suggestion je développe également quelque chose en ce sens ;)

Merci pour ton retour
