### ISSUE TITLE
TypeError: events[i].element is null

### ISSUE THREAD

**Issue by hidrarga** [kernox/Mastodon-Share-for-WordPress#18]
As I was saying in #16, I get a `TypeError: events[i].element is null` from toot_editor.js line 117:4, on every page, but not on articles. I'm using Firefox 58. This error doesn't seem to occur with Chromium.

**Comment by kernox** [comment]
What is your operating system please ?

**Comment by hidrarga** [comment]
Linux openSUSE Leap 42.3

**Comment by kernox** [comment]
Hi !

I have tested in the same configuration as yours.

I don't have this issue, but i have this : 
Use of Mutation Events is deprecated. Use MutationObserver instead.
toot_editor.js:117:3

Possibly the same issue, named differently
Do you have this error message too ?

On my side, it's not a fatal issue, the toot is generated well.

![virtualbox_open suse leap 42 3_07_02_2018_15_17_39](https://user-images.githubusercontent.com/10383373/35921126-17a68dfe-0c1a-11e8-9d25-a9ba65e3c527.png)

**Comment by hidrarga** [comment]
Hmm en fait je viens de tester avec le Firefox (v58) de mon Android, et j'obtiens toujours la même erreur... Je me demande si ce n'est pas mon installation wordpress qui pose problème. Pour info, j'utilise wordpress en multisite. Je vais tester avec d'autres wordpress pour voir.

Et je n'ai pas le warning dont tu parles :/

**Comment by hidrarga** [comment]
Voilà, je confirme : j'ai dû réinstaller (supprimer puis installer à nouveau) le plugin, et là ça fonctionne nickel :) Le problème venait donc bien de là...
