### ISSUE TITLE
[Mastodon Share 1.2] Bouton "Mettre à jour" inactif dans l'éiteur de billet

### ISSUE THREAD

**Issue by SGallay** [kernox/Mastodon-Share-for-WordPress#19]
Je viens d'installer Mastodon Share 1.2; j'ai toujours le problème de ne pas arriver à me connecter à l'imnstance, mais j'ai également constaté, en faisant une correction sur un article publié, que je ne pouvais plus enregistrer les changements avec le bouton "Mettre à jour": cliquer sur le bouton ne donne aucun résultat.

En désactivant le plug-in Mastodon Share, le bouton fonctionnait de nouveau.

(Wordpress 4.9.2)

**Comment by Ol-e** [comment]
En fait, pour se connecter à l'instance il faut bien vérifier que l'adresse comporte le bon protocole (http ou https) correspondant à l'instance en question. 
J'imagine que ça devrait se faire tout seul, mais à priori c'est http qui est pris en compte par default. Donc si c'est https, il faut le spécifier. De cette façon ça marche impec ! 
(également bien penser à mettre le domaine de l'instance en liste blanche pour les popups dans le navigateur)

**Comment by SGallay** [comment]
Oui, mais ça n'a pas vraiment de rapport avec mon problème.

**Comment by Ol-e** [comment]
Ah pardon, j'avais cru 

> j'ai toujours le problème de ne pas arriver à me connecter à l'imnstance,
