### ISSUE TITLE
Erreur: L'authentification du client a échoué à cause d'un client inconnu

### ISSUE THREAD

**Issue by hgoffin** [kernox/Mastodon-Share-for-WordPress#2]
Pour reproduire ce bug:
1. Récupérer la clé d'une instance mastodon X (sans forcément sauvegarder la configuration)
2. Récupérer la clé d'une instance mastodon Y

Message d'erreur: `L'authentification du client a échoué à cause d'un client inconnu, d'aucune authentification de client incluse ou d'une méthode d'authentification non prise en charge.`

Pour contourner ce bug, il m'a suffit de supprimer le fichier `tootophp.json` situé dans `wp-content/wp-mastodon-share/tootophp`. Cela permet en effet de regénérer le secret du client.

**Comment by kernox** [comment]
Bien vu. La prochaine version corrigera ce problème en supprimant le fichier tootophp.json lors de la demande d'une nouvelle clé.

**Comment by kernox** [comment]
Le bug est corrigé
