### ISSUE TITLE
Issue with Chars limit

### ISSUE THREAD

**Issue by Letiteuf55** [kernox/Mastodon-Share-for-WordPress#20]
Since the 1.2 update i have an issue with Chars.
For my last article there is : "2436 / 200"
The formatting is KO. 
The rules I defined are not taken into account.

**Comment by kernox** [comment]
Hi!
Thanks for your message. What is your browser, which version and under what operating system ?

**Comment by Letiteuf55** [comment]
Any browser, any OS.
It's on wordpress 4.9.2
![capture d ecran 2018-02-03 a 10 36 08](https://user-images.githubusercontent.com/23027090/35765900-29ac7c74-08ce-11e8-9a76-56e0c51e234f.png)

**Comment by Raymondcal** [comment]
Same here.
Before, the content of the toot editor was automatically blocked at 500 chars, even if you type a looongg note in your Wordpress editor.
Now, all chars of the Wordpress editor are copied into the Toot editor, regardless of the length of your note.

**Comment by kernox** [comment]
Hi !
This bug will be fixed in the next version.
Stay in touch
