### ISSUE TITLE
Toots when a draft is saved

### ISSUE THREAD

**Issue by teslasmoustache** [kernox/Mastodon-Share-for-WordPress#21]
I saved an un-published draft and it published a toot.

**Comment by kernox** [comment]
Hi !

Thanks for your report. This bug will be fixed in next version.

**Comment by Raymondcal** [comment]
Good !
I discovered this bug against my will! :)
What a surprise! :D

**Comment by kernox** [comment]
Update coming soon, but winter is already here.
