### ISSUE TITLE
Excerpt tronqué

### ISSUE THREAD

**Issue by hgoffin** [kernox/Mastodon-Share-for-WordPress#3]
Lorsqu'il y a deux liens dans l'excerpt, celui-ci est tronqué avant l'un des deux liens. En outre, tout ce qui se situe après l'excerpt est également tronqué, tels que le lien vers l'article, des hashtags, etc. 

Je n'ai pas pu reproduire ce bug avec un seul lien dans l'excerpt.

**Comment by kernox** [comment]
La prochaine version régle en partie ce problème. Un aperçu éditable du toot permettra de corriger les éventuels liens tronqués. Il n'est pas évident de détecter si la fin de l'excerpt vas ou non tomber au milieu d'un lien hypertexte.

**Comment by hgoffin** [comment]
Dans la mesure où Mastodon ne gère à ma connaissance aucun formatage (type Markdown), tu ne peux pas juste enlever toutes les balises html avant de tronquer l'excerpt ?

**Comment by kernox** [comment]
Le problème des balises et résolu dans la prochaine version. Je retire en effet les balises html mais dans le cas de blocs <a href="">Pouet !</a> Le titre du lien reste.

Seulement si on a un code du style : 

<a href="http://www.google.fr">http://www.google.fr</a>

Il y a un risque que le titre du lien soit tronqué et c'est difficilement évitable.

Une solution serait de tronquer en découpant le contenu par espaces ainsi seuls les mots entiers apparaîtrait.

**Comment by hgoffin** [comment]
À priori, ce cas de figure ne devrait pas se produire très souvent, j'imagine :)

Je pense effectivement que ce serait une bonne idée de tronquer le texte de façon à ne garder que des mots entiers :) Apparemment, c'est assez facile à faire : https://stackoverflow.com/questions/79960/how-to-truncate-a-string-in-php-to-the-word-closest-to-a-certain-number-of-chara (normalement les `\n` ne devraient pas poser de problème, puisque l'excerpt est en html ?)

**Comment by kernox** [comment]
Merci de mettre a jour votre extension sur WordPress. La version 0.9 corrige ce bug.
