### ISSUE TITLE
freebsd php70 Error: Call to undefined function mime_content_type()

### ISSUE THREAD

**Issue by vsatmydynipnet** [kernox/Mastodon-Share-for-WordPress#32]
I get

Error: Call to undefined function mime_content_type()

since I updated to 1.4 on FreeBSD using php70 on one server, and php56 on another one. 

Worked perfect till now. :-(

**Comment by kernox** [comment]
Please verify you have the fileinfo extension enabled on both php version.

**Comment by vsatmydynipnet** [comment]
THANK YOU! All works fine now.
