### ISSUE TITLE
Billets planifiés

### ISSUE THREAD

**Issue by SGallay** [kernox/Mastodon-Share-for-WordPress#4]
Le partage automatique ne fonctionne pas avec les billets planifiés. Il faut revenir sur le billet, faire une modification mineure et la sauvegarder pour activer le toot.

**Comment by kernox** [comment]
Oui en effet et c'est normal car WordPress pour planifier les billet saisi un timestamp dans la base de donnée qui correspond à la date ou l'article devra s'afficher. À chaque chargement de la page qui liste les articles, WordPress verifie ce timestamp. Si la le couple date heure dépassé ce timestamp alors l'article est affiché. Il n'y a pas à proprement parler de publication qui est déclenchée.

Je n'ai pas de solution aujourd'hui pour gérer les billets planifiés.

**Comment by SGallay** [comment]
Ah, OK. Ben tant pis, je fonctionne surtout avec des billets planifiés. Je m'en accommoderai.
---
Stephane 'Alias' Gallay -- stephane.gallay@me.com
https://alias.erdorin.org 
Ceci n'est pas une signature.

Le 3 août 2017 à 13:48, kernox <notifications@github.com> a écrit :

Oui en effet et c'est normal car WordPress pour planifier les billet saisi un timestamp dans la base de donnée qui correspond à la date ou l'article devra s'afficher. À chaque chargement de la page qui liste les articles, WordPress verifie ce timestamp. Si la le couple date heure dépassé ce timestamp alors l'article est affiché. Il n'y a pas à proprement parler de publication qui est déclenchée.
Je n'ai pas de solution aujourd'hui pour gérer les billets planifiés.

**Comment by kernox** [comment]
Néanmoins je vais essayer de trouver une solution à ce problème. Si un hook wordpress existe pour ça ce sera simple sinon ça prendra un peu plus de temps.

**Comment by SGallay** [comment]
J'imagine que les autres outils de publication qui fonctionnent avec des articles planifiés, comme le module Publicize de Jetpack, doivent bien utiliser un truc.
---
Stephane 'Alias' Gallay -- stephane.gallay@me.com
https://alias.erdorin.org 
Ceci n'est pas une signature.

Le 3 août 2017 à 14:13, kernox <notifications@github.com> a écrit :

Néanmoins je vais essayer de trouver une solution à ce problème. Si un hook wordpress existe pour ça ce sera simple sinon ça prendra un peu plus de temps.

**Comment by kernox** [comment]
Bonjour,
Cette fonctionnalité n'est pas dans les priorités pour le moment.

**Comment by kernox** [comment]
La nouvelle version 1.2, inclus le support des articles planifiés.
Merci de mettre à jour l'extension
