### ISSUE TITLE
planed posts don't get pushed to mastodon

### ISSUE THREAD

**Issue by SunDancerGE** [kernox/Mastodon-Share-for-WordPress#5]
Publishing an article - Toot on Mastodon works (Tweet goes out)
Edit an article - Toot on Mastodon works  (Tweet goes out)
Plan publishing an article - no toot.  (Tweet goes out)

What to do?

**Comment by kernox** [comment]
This issue is knowed, no solution for this yet.

WordPress have not a real schedule system for the post. It's an illusion created by a planning date. When the post date defined is passed, the post appear. But no event or action called.

I search a solution to do this.

**Comment by SunDancerGE** [comment]
I knwo for a fact that "planned articles" are posted when someone visits the blog after "planned date". The WP to Twitter Plugin works fine. Maybe sneak up on them how they solved it?

**Comment by kernox** [comment]
Sorry but this feature is not in priority yet.

Stay in touch

**Comment by kernox** [comment]
New version available with this feature, please update ;)
