### ISSUE TITLE
URL de l'article n'est pas partagée

### ISSUE THREAD

**Issue by SGallay** [kernox/Mastodon-Share-for-WordPress#6]
Il arrive que, sur certains messages, l'URL n'apparaisse pas. Je ne sais pas trop pourquoi, je dois dire...

Par exemple: https://framapiaf.org/@Alias/98979102071970074/

**Comment by kernox** [comment]
Si c'est un nouvel article les informations pour constituer l'URL ne sont pas disponible dés le départ dans les sources HTML ou JS. De ce fait il faut attendre l'autosave de wordpress pour que l'url soit generée.

Je travail justement à regler ça.

**Comment by kernox** [comment]
La derniere version corrige normalement ce bug. Je ferme le ticket ;)
